### ISSUE TITLE
Minimum Functionality on ProfilePage

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#118]
1. Make These Fields Editable with Proper Styling Buttons:

Mark as Public Info

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/d712fef1-f2bd-4a70-98d1-0eb93bf2eef8)

Emoji lists:

https://unicode.org/emoji/charts/full-emoji-list.html

https://gist.github.com/rxaviers/7360908

https://gist.github.com/roachhd/1f029bd4b50b8a524f3c

2. Put Divider Line Between Private Info

3. Financial Stats... Put Coming Soon Other Than Basics, Particularly Maximum Debt Limit

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/30eef8d1-902d-4c7d-9669-08dc8ea3acd9)

4. Portfolio...Let's Show Position Rather than Trades

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/9b3b42bc-254a-453e-bc0d-ea2bc8d7041b)

**Comment by pwdel** [comment]
In addition to the above, we have the following bug when you open a profilepage:

```
chunk-MZ6XKLY2.js?v=27f03ac2:519 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <td>.
    at tr
    at td
    at tr
    at tbody
    at table
    at div
    at Profile (http://localhost:8089/src/pages/profile/Profile.jsx:25:35)
    at Route2 (http://localhost:8089/node_modules/.vite/deps/react-router-dom.js?v=67abb527:2835:29)
    at Switch2 (http://localhost:8089/node_modules/.vite/deps/react-router-dom.js?v=67abb527:2979:29)
    at AppRoutes (http://localhost:8089/src/helpers/AppRoutes.jsx:36:26)
    at header
    at div
    at Router2 (http://localhost:8089/node_modules/.vite/deps/react-router-dom.js?v=67abb527:2548:30)
    at BrowserRouter2 (http://localhost:8089/node_modules/.vite/deps/react-router-dom.js?v=67abb527:3096:35)
    at AuthProvider (http://localhost:8089/src/helpers/AuthContent.jsx:33:25)
    at App
```

**Comment by pwdel** [comment]
Split up project:

1. Private Functions:

Edit these, each a component:

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/d5dbf479-11cf-453f-93db-dd7f64697aec)


2. Public Functions:

Turn this into a component:


![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/01028197-e97e-49e3-904c-e63dc8b46dcb)

Each line that we are going to use could be a component. Push anything extra or anything that takes work into a future project.

**Comment by pwdel** [comment]
Password reset..?

With a, "Warning, we don't have an automatic password reset function. Please keep your password safe as we may have no way to return it and it may have to be manually reset by an administrator if it gets lost."

**Comment by pwdel** [comment]
Note .... maybe look into OpenID? https://openid.net/

**Comment by pwdel** [comment]
@markokovac16 working on improving the profilepage per your comment here:

https://github.com/openpredictionmarkets/socialpredict/issues/125#issuecomment-2118990755

> Conditional rendering sorts out these issues ... I like to implement a loader until the data is pulled and rendered in order to ensure these errors don't happen ... If there's no data, render a relevant message

**Comment by pwdel** [comment]
We're now doing conditional loading and updated a bunch of buttons. Only the emoji and description buttons works but other ones will come soon.


![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/83064ac3-c185-4e9b-a60c-81d8da50467e)
