### ISSUE TITLE
Fix Weird Edge Case Shares Rounding Math - Resulting in Being Able to Sell Shares Shouldn't Have and Breaking Profile Page

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#121]
![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/b9a37410-c975-4507-8358-b83ad63d8882)

**Comment by pwdel** [comment]
```
2024/05/12 11:56:25 claims.Username is user1
2024/05/12 11:56:25 Extracted username: user1
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go: ] Variable Name: 'R', Type: float64, Value: 0.525
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:$] Variable Name: 'S', Type: float64, Value: 19
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:)] Variable Name: 'S_YES', Type: float64, Value: 10
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:+] Variable Name: 'S_NO', Type: float64, Value: 9
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:D] Variable Name: 'coursePayouts', Type: []dbpm.CourseBetPayout, Length: 12, Value: [{0.2500000000000002 YES} {0.42954545454545456 YES} {4.766666666666667 NO} {0.025000000000000022 YES} {-0.004166666666666652 YES} {0.025000000000000022 YES} {-0.004166666666666652 YES} {0.025000000000000022 NO} {-0.04583333333333334 NO} {-0.025000000000000022 NO} {-0.002272727272727315 YES} {-0.025000000000000022 NO}]
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:V] Variable Name: 'C_YES_SUM', Type: float64, Value: 0.7189393939393942
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:W] Variable Name: 'C_NO_SUM', Type: float64, Value: 4.695833333333333
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:g] Variable Name: 'F_YES', Type: float64, Value: 13.909378292939932
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:h] Variable Name: 'F_NO', Type: float64, Value: 1.9165927240461405
2024/05/12 11:56:25 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:
                                                                               ] Variable Name: 'scaledPayouts', Type: []int64, Length: 12, Value: [3 6 9 0 0 0 0 0 0 0 0 0]
```

**Comment by pwdel** [comment]
This later leads to not being able to trade on the market and not being able to fetch user shares:

![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/d24e3b85-36fd-40c0-8444-aaabe970553b)

```
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go: ] Variable Name: 'R', Type: float64, Value: 0.5681818181818182
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:$] Variable Name: 'S', Type: float64, Value: 21
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:)] Variable Name: 'S_YES', Type: float64, Value: 12
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:+] Variable Name: 'S_NO', Type: float64, Value: 9
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:D] Variable Name: 'coursePayouts', Type: []dbpm.CourseBetPayout, Length: 16, Value: [{0.6818181818181823 YES} {0.38636363636363635 YES} {4.291666666666666 NO} {0.06818181818181823 YES} {-0.04734848484848486 YES} {0.06818181818181823 YES} {-0.04734848484848486 YES} {0.06818181818181823 NO} {-0.08901515151515155 NO} {-0.06818181818181823 NO} {-0.045454545454545525 YES} {-0.06818181818181823 NO} {0.04318181818181821 YES} {0.02056277056277056 YES} {0 YES} {-0.018774703557312256 YES}]
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:V] Variable Name: 'C_YES_SUM', Type: float64, Value: 1.109363824581217
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:W] Variable Name: 'C_NO_SUM', Type: float64, Value: 4.134469696969696
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:g] Variable Name: 'F_YES', Type: float64, Value: 10.817010374869561
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:h] Variable Name: 'F_NO', Type: float64, Value: 2.1768208886852958
2024/05/12 12:30:35 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:
                                                                               ] Variable Name: 'scaledPayouts', Type: []int64, Length: 16, Value: [7 4 9 1 -1 1 -1 0 0 0 0 0 0 0 0 0]
```

Shares fetch:


![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/f2370789-8f87-4641-a61d-bd56fae61267)

**Comment by pwdel** [comment]
![Image](https://github.com/openpredictionmarkets/socialpredict/assets/13304149/d5a4f822-44d2-44a9-b6ee-633b2d673d86)

**Comment by pwdel** [comment]
If we have the following bet vector:

```
Outcome: Y, Y, N, N, N
Amount: 1, -1, 1, -1, 1
Position After: 1, 0, 1, 0, 2
Prob After: 75, 50, 25, 50, 25
```

The next transaction attempting to sell the two NO shares results in an error.

```
marketDetailsUtils.jsx:17 Error fetching market data: SyntaxError: Unexpected end of JSON input
    at fetchData (marketDetailsUtils.jsx:14:45)
fetchData @ marketDetailsUtils.jsx:17
await in fetchData (async)
(anonymous) @ marketDetailsUtils.jsx:21
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
commitPassiveMountOnFiber @ chunk-MZ6XKLY2.js?v=27f03ac2:18150
commitPassiveMountEffects_complete @ chunk-MZ6XKLY2.js?v=27f03ac2:18123
commitPassiveMountEffects_begin @ chunk-MZ6XKLY2.js?v=27f03ac2:18113
commitPassiveMountEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:18103
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19484
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:19322
workLoop @ chunk-MZ6XKLY2.js?v=27f03ac2:195
flushWork @ chunk-MZ6XKLY2.js?v=27f03ac2:174
performWorkUntilDeadline @ chunk-MZ6XKLY2.js?v=27f03ac2:382
Show 11 more frames
Show less
VM495:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at fetchBets (BetsActivity.jsx:13:45)
fetchBets @ BetsActivity.jsx:13
await in fetchBets (async)
(anonymous) @ BetsActivity.jsx:19
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
commitPassiveMountOnFiber @ chunk-MZ6XKLY2.js?v=27f03ac2:18150
commitPassiveMountEffects_complete @ chunk-MZ6XKLY2.js?v=27f03ac2:18123
commitPassiveMountEffects_begin @ chunk-MZ6XKLY2.js?v=27f03ac2:18113
commitPassiveMountEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:18103
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19484
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 12 more frames
Show less
VM496:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at fetchBets (BetsActivity.jsx:13:45)
fetchBets @ BetsActivity.jsx:13
await in fetchBets (async)
(anonymous) @ BetsActivity.jsx:19
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
invokePassiveEffectMountInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:18318
invokeEffectsInDev @ chunk-MZ6XKLY2.js?v=27f03ac2:19695
commitDoubleInvokeEffectsInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:19680
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19497
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 11 more frames
Show less
VM497:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at fetchBets (BetsActivity.jsx:13:45)
fetchBets @ BetsActivity.jsx:13
await in fetchBets (async)
(anonymous) @ BetsActivity.jsx:19
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
commitPassiveMountOnFiber @ chunk-MZ6XKLY2.js?v=27f03ac2:18150
commitPassiveMountEffects_complete @ chunk-MZ6XKLY2.js?v=27f03ac2:18123
commitPassiveMountEffects_begin @ chunk-MZ6XKLY2.js?v=27f03ac2:18113
commitPassiveMountEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:18103
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19484
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 12 more frames
Show less
VM498:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at fetchBets (BetsActivity.jsx:13:45)
fetchBets @ BetsActivity.jsx:13
await in fetchBets (async)
(anonymous) @ BetsActivity.jsx:19
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
invokePassiveEffectMountInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:18318
invokeEffectsInDev @ chunk-MZ6XKLY2.js?v=27f03ac2:19695
commitDoubleInvokeEffectsInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:19680
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19497
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 11 more frames
Show less
PositionsActivity.jsx:10 
        
        
       GET http://localhost:8089/api/v0/markets/positions/4 504 (Gateway Time-out)
fetchPositions @ PositionsActivity.jsx:10
(anonymous) @ PositionsActivity.jsx:22
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
commitPassiveMountOnFiber @ chunk-MZ6XKLY2.js?v=27f03ac2:18150
commitPassiveMountEffects_complete @ chunk-MZ6XKLY2.js?v=27f03ac2:18123
commitPassiveMountEffects_begin @ chunk-MZ6XKLY2.js?v=27f03ac2:18113
commitPassiveMountEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:18103
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19484
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 12 more frames
Show less
PositionsActivity.jsx:19 Error fetching positions: Gateway Time-out
fetchPositions @ PositionsActivity.jsx:19
await in fetchPositions (async)
(anonymous) @ PositionsActivity.jsx:22
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
commitPassiveMountOnFiber @ chunk-MZ6XKLY2.js?v=27f03ac2:18150
commitPassiveMountEffects_complete @ chunk-MZ6XKLY2.js?v=27f03ac2:18123
commitPassiveMountEffects_begin @ chunk-MZ6XKLY2.js?v=27f03ac2:18113
commitPassiveMountEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:18103
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19484
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 12 more frames
Show less
PositionsActivity.jsx:10 
        
        
       GET http://localhost:8089/api/v0/markets/positions/4 504 (Gateway Time-out)
fetchPositions @ PositionsActivity.jsx:10
(anonymous) @ PositionsActivity.jsx:22
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
invokePassiveEffectMountInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:18318
invokeEffectsInDev @ chunk-MZ6XKLY2.js?v=27f03ac2:19695
commitDoubleInvokeEffectsInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:19680
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19497
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 11 more frames
Show less
PositionsActivity.jsx:19 Error fetching positions: Gateway Time-out
fetchPositions @ PositionsActivity.jsx:19
await in fetchPositions (async)
(anonymous) @ PositionsActivity.jsx:22
commitHookEffectListMount @ chunk-MZ6XKLY2.js?v=27f03ac2:16902
invokePassiveEffectMountInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:18318
invokeEffectsInDev @ chunk-MZ6XKLY2.js?v=27f03ac2:19695
commitDoubleInvokeEffectsInDEV @ chunk-MZ6XKLY2.js?v=27f03ac2:19680
flushPassiveEffectsImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19497
flushPassiveEffects @ chunk-MZ6XKLY2.js?v=27f03ac2:19441
commitRootImpl @ chunk-MZ6XKLY2.js?v=27f03ac2:19410
commitRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:19271
performSyncWorkOnRoot @ chunk-MZ6XKLY2.js?v=27f03ac2:18889
flushSyncCallbacks @ chunk-MZ6XKLY2.js?v=27f03ac2:9133
(anonymous) @ chunk-MZ6XKLY2.js?v=27f03ac2:18621
Show 11 more frames
Show less
```

Ultimately this seems to be because the underlying data response is invalid.

We get the following backend calculations which include an infinite condition immediately prior:

```
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go: ] Variable Name: 'R', Type: float64, Value: +Inf
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:$] Variable Name: 'S', Type: float64, Value: -1
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:)] Variable Name: 'S_YES', Type: float64, Value: -Inf
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:+] Variable Name: 'S_NO', Type: float64, Value: +Inf
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:D] Variable Name: 'coursePayouts', Type: []dbpm.CourseBetPayout, Length: 6, Value: [{+Inf YES} {-Inf YES} {+Inf NO} {-Inf NO} {+Inf NO} {-Inf NO}]
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:V] Variable Name: 'C_YES_SUM', Type: float64, Value: NaN
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:W] Variable Name: 'C_NO_SUM', Type: float64, Value: NaN
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:g] Variable Name: 'F_YES', Type: float64, Value: 1
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:h] Variable Name: 'F_NO', Type: float64, Value: 1
socialpredict-backend-container-dev  | 2024/05/13 15:00:38 [/backend/handlers/math/outcomes/dbpm/dbpm_marketshares.go:] Variable Name: 'scaledPayouts', Type: []int64, Length: 6, Value: [-9223372036854775808 -9223372036854775808 -9223372036854775808 -9223372036854775808 -9223372036854775808 -9223372036854775808]

```

**Comment by pwdel** [comment]
Resources, things to change:

https://github.com/openpredictionmarkets/socialpredict/blob/profilepage/README/README-MATH-PROB-AND-PAYOUT.md
